### ISSUE TITLE
mic_vad_streaming.py: Can't parse .tflite model as binary proto

### ISSUE THREAD

**Issue by wattahay** [mozilla/DeepSpeech-examples#100]
When attempting to run the .tflite and default scorer with .9.3,
the model file cannot be read as "binary proto"

**Steps to Reproduce**

1. python3.8 -m venv deepspeech
2. source /home/path/venv/bin/activate
3. pip install -r requirements.txt

> deepspeech~=0.9.3
> pyaudio~=0.2.11
> webrtcvad~=2.0.10
> halo~=0.0.18
> numpy>=1.15.1
> scipy>=1.1.0

4. Download .tflite file, and .scorer file from 0.9.3 release page
5. Download mic_vad_streaming.py from this GitHub repo
6. python mic_vad_streaming.py -m deepspeech-0.9.3-models.tflite -s deepspeech-0.9.3-models.scorer

**Results:**

> $ python mic_vad_streaming.py -m deepspeech-0.9.3-models.tflite -s deepspeech-0.9.3-models.scorer 
> Initializing model...
> INFO:root:ARGS.model: deepspeech-0.9.3-models.tflite
> TensorFlow: v2.3.0-6-g23ad988
> DeepSpeech: v0.9.3-0-gf2e9c85
> Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
> Data loss: Can't parse deepspeech-0.9.3-models.tflite as binary proto
> Traceback (most recent call last):
>   File "mic_vad_streaming.py", line 226, in <module>
>     main(ARGS)
>   File "mic_vad_streaming.py", line 164, in main
>     model = deepspeech.Model(ARGS.model)
>   File "/home/path/venv/lib64/python3.8/site-packages/deepspeech/__init__.py", line 38, in __init__
>     raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
> RuntimeError: CreateModel failed with 'Error reading the proto buffer model file.' (0x3005)
> 
>

**Comment by lissyx** [comment]
Change requirements to pull deepspeech-tflite module, this is not a bug.

**Comment by Abdulazizbek** [comment]
The same problem.
How to pull `deepspeech-tflite` module, is there any code example, please?

**Comment by wattahay** [comment]
It's a bug if needing to update the repo is a bug.

The requirements.txt file still reads deepspeech .8 and does not include deepspeech-tflite.

Abdulazizbek:
You use something like:
pip install --user --update deepspeech-tflite

**Comment by Abdulazizbek** [comment]
Yes, requirement.txt file uses deepspeech .8, but in my case I am using .9 for both tflite and deepspeech

**Comment by lissyx** [comment]
> The same problem.
> How to pull `deepspeech-tflite` module, is there any code example, please?

Change requirements.txt dependency

**Comment by lissyx** [comment]
> It's a bug if needing to update the repo is a bug.
> 
> The requirements.txt file still reads deepspeech .8, though it is specifically for .9,
> and it does not include deepspeech-tflite.
> 
> Abdulazizbek:
> You use something like:
> pip install --user --update deepspeech-tflite

Both modules have the same interface but they are still differents python modules so its not a bug.
