### ISSUE TITLE
Can't get text by mic_vad_streaming.py from 2830-3980-0043.wav

### ISSUE THREAD

**Issue by moneypi** [mozilla/DeepSpeech-examples#11]
Ubuntu 19.04 
Python 3.7.3

I just clone this project, then when I run
```
cd mic_vad_streaming
./test.sh 
I get an error:
++ dirname ./test.sh
+ THIS=.
+ pushd .
~/DeepSpeech/DeepSpeech-examples/mic_vad_streaming ~/DeepSpeech/DeepSpeech-examples/mic_vad_streaming
+ source ../tests.sh
++ set -xe
+++ dirname ./test.sh
++ THIS=.
++ source ../../taskcluster/tc-tests-utils.sh
+++ set -xe
++++ uname
+++ export OS=Linux
+++ OS=Linux
+++ '[' Linux = Linux ']'
+++ export DS_ROOT_TASK=/home/tensorflow
+++ DS_ROOT_TASK=/home/tensorflow
+++ '[' Linux = '' ']'
+++ '[' Linux = Darwin ']'
+++ export TASKCLUSTER_ARTIFACTS=/tmp/artifacts
+++ TASKCLUSTER_ARTIFACTS=/tmp/artifacts
+++ export TASKCLUSTER_TMP_DIR=/tmp
+++ TASKCLUSTER_TMP_DIR=/tmp
+++ export ANDROID_TMP_DIR=/data/local/tmp
+++ ANDROID_TMP_DIR=/data/local/tmp
+++ mkdir -p /tmp
+++ export DS_TFDIR=/home/tensorflow/DeepSpeech/tf
+++ DS_TFDIR=/home/tensorflow/DeepSpeech/tf
+++ export DS_DSDIR=/home/tensorflow/DeepSpeech/ds
+++ DS_DSDIR=/home/tensorflow/DeepSpeech/ds
+++ export DS_EXAMPLEDIR=/home/tensorflow/DeepSpeech/examples
+++ DS_EXAMPLEDIR=/home/tensorflow/DeepSpeech/examples
++++ cat /home/tensorflow/DeepSpeech/ds/VERSION
cat: /home/tensorflow/DeepSpeech/ds/VERSION: 没有那个文件或目录
+++ export DS_VERSION=
+++ DS_VERSION=
+++ export ANDROID_SDK_HOME=/home/tensorflow/DeepSpeech/Android/SDK/
+++ ANDROID_SDK_HOME=/home/tensorflow/DeepSpeech/Android/SDK/
+++ export ANDROID_NDK_HOME=/home/tensorflow/DeepSpeech/Android/android-ndk-r18b/
+++ ANDROID_NDK_HOME=/home/tensorflow/DeepSpeech/Android/android-ndk-r18b/
+++ WGET=wget
+++ TAR=tar
+++ XZ='pixz -9'
+++ UNXZ='pixz -d'
+++ '[' Linux = '' ']'
+++ model_source=
++++ basename ''
+++ model_name=
++++ basename -s .pb ''
+++ model_name_mmap=.pbmm
++++ dirname ''
+++ model_source_mmap=./.pbmm
+++ SUPPORTED_PYTHON_VERSIONS='2.7.16:ucs2 2.7.16:ucs4 3.5.7:ucs4 3.6.8:ucs4 3.7.3:ucs4 3.8.0:ucs4'
+++ SUPPORTED_NODEJS_VERSIONS='4.9.1 5.12.0 6.17.1 7.10.1 8.16.0 9.11.2 10.16.0 11.15.0 12.5.0 13.0.1'
+++ SUPPORTED_ELECTRONJS_VERSIONS='1.6.18 1.7.16 1.8.8 2.0.18 3.0.16 3.1.11 4.0.3 4.1.5 4.2.5 5.0.6 6.0.11 7.0.1 7.1.2'
+++ python -c 'import json; import sys; print(" ".join(json.loads(sys.stdin.read())["dependencies"]));'
+++ curl -s https://community-tc.services.mozilla.com/api/queue/v1/task/
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'dependencies'
++ DEP_TASK_ID=
```

If I run 
python3 mic_vad_streaming.py \
  --model deepspeech-0.6.0-models/output_graph.pbmm \
  --lm deepspeech-0.6.0-models/lm.binary \
  --trie deepspeech-0.6.0-models/trie
I can get text from microphone.

But if I run 
python3 mic_vad_streaming.py \
  --model deepspeech-0.6.0-models/output_graph.pbmm \
  --lm deepspeech-0.6.0-models/lm.binary \
  --trie deepspeech-0.6.0-models/trie
  --file audio/2830-3980-0043.wav
I didn't get any text.
Event run in Ubuntu 19.10/**RTX2060**, I can't get any text.

If I run 
deepspeech --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie --audio audio/2830-3980-0043.wav
I can get "experience proof less"

So, how can I get right result by run 
python3 mic_vad_streaming.py \
  --model deepspeech-0.6.0-models/output_graph.pbmm \
  --lm deepspeech-0.6.0-models/lm.binary \
  --trie deepspeech-0.6.0-models/trie
  --file audio/2830-3980-0043.wav

**Comment by moneypi** [comment]
When I open https://community-tc.services.mozilla.com/api/queue/v1/task/, I get 
{
  "error": "Not found"
}

**Comment by lissyx** [comment]
> ./test.sh
> [...]
> When I open https://community-tc.services.mozilla.com/api/queue/v1/task/, I get
> {
> "error": "Not found"
> }

You are not supposed to use `test.sh`, so that's normal.

**Comment by moneypi** [comment]
@lissyx Then, what I supposed to do?
Thanks.

**Comment by lissyx** [comment]
> @lissyx Then, what I supposed to do?
> Thanks.

I don't understand your question. You seem to be able to run the tool, and it works. I have no idea why this file returns no transcription, but others works, and from your microphone, it works ...

**Comment by lissyx** [comment]
@moneypi Ping ? Can you share more informations ?

**Comment by moneypi** [comment]
@lissyx I'm sorry,I don't know what kind information can I provide.
I am trying another project, https://github.com/apache/incubator-mxnet/tree/master/example/speech_recognition.
