### ISSUE TITLE
errno 2

### ISSUE THREAD

**Issue by adaaaaaa** [mozilla/DeepSpeech-examples#110]
[captain@captain-notebook vad_transcriber]$ python audioTranscript_gui.py 
audioTranscript_gui.py - initUI@169 root:DEBUG  Multithreading with maximum 8 threads
audioTranscript_gui.py - mic_activate@173 root:DEBUG  Enable streaming widgets
audioTranscript_gui.py - models_on_click@207 root:DEBUG  Models Browse Button clicked
audioTranscript_gui.py - models_on_click@211 root:DEBUG  /home/captain/software/DeepSpeech-examples/mic_vad_streaming
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x563794889ae0), parent's thread is QThread(0x5637944946f0), current thread is QThreadPoolThread(0x5637950b20e0)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
wavTranscriber.py - resolve_models@62 root:DEBUG  Found Model: /home/captain/software/DeepSpeech-examples/mic_vad_streaming/deepspeech-0.9.3-models-zh-CN.pbmm
wavTranscriber.py - resolve_models@65 root:DEBUG  Found scorer: /home/captain/software/DeepSpeech-examples/mic_vad_streaming/deepspeech-0.9.3-models-zh-CN.scorer
TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.3-0-gf2e9c85
2021-01-15 16:29:25.510221: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
wavTranscriber.py - load_model@20 root:DEBUG  Loaded model in 0.035s.
wavTranscriber.py - load_model@25 root:DEBUG  Loaded external scorer in 0.001s.
audioTranscript_gui.py - openMicrophone_on_click@272 root:DEBUG  Preparing to open microphone...
audioTranscript_gui.py - openMicrophone_on_click@283 root:DEBUG  Start Recording pressed
audioTranscript_gui.py - openMicrophone_on_click@284 root:DEBUG  Preparing for transcription...
Traceback (most recent call last):
  File "audioTranscript_gui.py", line 287, in openMicrophone_on_click
    subproc = subprocess.Popen(shlex.split('rec -q -V0 -e signed -L -c 1 -b 16 -r 16k -t raw - gain -2'),
  File "/home/captain/.pyenv/versions/3.8.6/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/captain/.pyenv/versions/3.8.6/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'rec'
已放弃 (核心已转储)

what's the problem

**Comment by lissyx** [comment]
> FileNotFoundError: [Errno 2]

Read your error ?

**Comment by lissyx** [comment]
unactionable and no feedback from reporter.
