### ISSUE TITLE
Can this model be used for Speaker Recognition

### ISSUE THREAD

**Issue by doctorwho-123** [mozilla/DeepSpeech-examples#118]
Hi,
I am working on Speaker Recognition. Is it possible to use this model for Speaker Recognition ?
If yes can you please guide me a little. And If not can you refer me some Deep Learning models which I can use for it.

**Comment by lissyx** [comment]
Please refer to https://github.com/mozilla/DeepSpeech https://deepspeech.readthedocs.io/ https://discourse.mozilla.org/c/deep-speech/247
