### ISSUE TITLE
How to stream via voice / speech microphone using C # and show stream speeh to text 

### ISSUE THREAD

**Issue by doctorwho-123** [mozilla/DeepSpeech-examples#120]
I read the following code

https://github.com/mozilla/DeepSpeech-examples/tree/r0.9/mic_vad_streaming
, but I want to receive only Weiss as a stream in C # using DeepSpeak and show me the text in the box list without pressing a button. I mean, the microphone is always active, but I do not know what to do. I tried very hard to change the following code, but unfortunately I do not know Python. Thank you very much for your help.

**Comment by lissyx** [comment]
Please reach for that kind of help on Discourse.
