### ISSUE TITLE
DeepSpeech app compilation error in android studio

### ISSUE THREAD

**Issue by andrejmz** [mozilla/DeepSpeech-examples#121]
Hi

When i try to run the demo app on android studio i have the enclosed compilation error.
How to solve it please ?

Best regards
![comperror](https://user-images.githubusercontent.com/53060718/109361428-3467c280-7889-11eb-8aee-3a1e40713fc0.png)

**Comment by lissyx** [comment]
Please follow the Github template and reach for support on Discourse.
