### ISSUE TITLE
Failed to resolve: ai.coqui:libstt:0.9.3

### ISSUE THREAD

**Issue by soudalan** [mozilla/DeepSpeech-examples#132]
After checking out the project and opening it in Android Studio (4.1), running the app throws this error:
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find ai.coqui:libstt:0.9.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/ai/coqui/libstt/0.9.3/libstt-0.9.3.pom
       - https://jcenter.bintray.com/ai/coqui/libstt/0.9.3/libstt-0.9.3.pom

**Comment by lissyx** [comment]
This repo is unrelated to coqui.
