### ISSUE TITLE
Cannot find module '../node_modules/deepspeech/lib/binding/v0.9.3/linux-x64/node-v93/deepspeech.node' in node v16.1.0

### ISSUE THREAD

**Issue by bobajeff** [mozilla/DeepSpeech-examples#138]
I'm having a similar issue to #48. Only with node v16.1.0 (which is the current release as of now).

**Comment by lissyx** [comment]
> I'm having a similar issue to #48. Only with node v16.1.0 (which is the current release as of now).

And which will have no NodeJS v16.

**Comment by orrburgel** [comment]
How do I downgrade to node-v88? it's unclear how to get that version number, tried:
```
>node -v
v16.13.2

>npm -v
8.3.1
```
And I'm looking for v88 which is the latest that seems to be supported in the `.../node_modules/deepspeech/lib/binding/v0.9.3/win32-x64..../node-v88``` (I don't really remember the path)

Online it says it's node v15 but there isn't any available download for v15 only v14 and v16 are being maintained:
https://nodejs.org/en/about/releases/

Looked everywhere:
https://nodejs.org/en/download/

**Comment by raphael10-collab** [comment]
I'm having the same issue with `node v16.13.0` which is current `LTS` node version: https://nodejs.org/en/

Any ideas abouw how to solve it?

**Comment by dushimsam** [comment]
migrating to nodeV14 things should work perfectly
