### ISSUE TITLE
uses for Indian language

### ISSUE THREAD

**Issue by lerndeep** [mozilla/DeepSpeech-examples#16]
I checked microphone streaming with the English language with pre-trained weight, it is working. please, could you explain how can I use this for another language? If I train network with other languages and use PB converted weight file for microphone streaming inferencing, can it work for me?

**Comment by kdavis-mozilla** [comment]
As this is not a bug or a feature request could you forward this request to our [discourse channel](https://discourse.mozilla.org/c/deep-speech/247). Thanks.
