### ISSUE TITLE
Update Readme with npm installation error avoidance

### ISSUE THREAD

**Issue by Duxy1996** [mozilla/DeepSpeech-examples#18]
You should add a new dependency requirement to run the **nodejs_mic_vad_streaming**
project. In a clean installation of Ubuntu 16.04 LTE x64 when you run the command 

```
npm install

```

this error appears:
```
Entering directory '/home/dev/Documents/speech/DeepSpeech-examples/nodejs_mic_vad_streaming/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
```
This means that you need to install the  **libasound2-dev** lib executing:

```
$ sudo apt-get install libasound2-dev
```

**Comment by lissyx** [comment]
@Duxy1996 Well, you are welcome to send a PR :-).
