### ISSUE TITLE
.Net Framework example missing DeepSpeechClient solution?

### ISSUE THREAD

**Issue by yafimski** [mozilla/DeepSpeech-examples#187]
Hi,
I cloned
https://github.com/mozilla/DeepSpeech-examples/tree/r0.9/net_framework/DeepSpeechWPF)
but it seems that the DeepSpeechClient solution is missing from the repo.

Is that correct? I think I won't be able to run the example without it.

**Comment by lissyx** [comment]
Project is not maintained anymore.
