### ISSUE TITLE
tc-tests-utils.sh not found

### ISSUE THREAD

**Issue by AbdouBou** [mozilla/DeepSpeech-examples#190]
Hello,
I'm trying to run the test.sh script in the main repo. i got an error 
$HOME$/DeepSpeech/ds/taskcluster/tc-tests-utils.sh not such file or directory.
When i check my home directory there is even No DeepSpeech Directory. Knowing that i correctly installed deepspeech (and all other dependencies). How can i have this folder please?

Thank you in advance

**Comment by lissyx** [comment]
this is not code to use for you. no doc points to it
