### ISSUE TITLE
Failed to execute startup script

### ISSUE THREAD

**Issue by quyuancheng** [mozilla/DeepSpeech-examples#216]
python3 autosub/main.py --model deepspeech-0.9.3-models.pbmm --scorer deepspeech-0.9.3-models.scorer --file ~/Downloads/1073497326-1-208.mp4

error info: 43335 illegal hardware instruction  python3 autosub/main.py --model deepspeech-0.9.3-models.pbmm --scorer  --file

My operating system is mac （M1）

**Comment by lissyx** [comment]
the binaries are not compatible with M1
