### ISSUE TITLE
mic_vad_streaming.py not working on Cloud Instance after providing --file argument

### ISSUE THREAD

**Issue by swapnil3597** [mozilla/DeepSpeech-examples#26]
I'm able to get  text output on my local machine from `mic_vad_streaming.py` by providing `.wav` file in `--file` argument. But while running this code on AWS ec2 instance and also Colab Notebook I'm getting this following error:
```
Traceback (most recent call last):
  File "mic_vad_streaming.py", line 237, in <module>
    main(ARGS)
  File "mic_vad_streaming.py", line 174, in main
    file=ARGS.file)
  File "mic_vad_streaming.py", line 107, in __init__
    super().__init__(device=device, input_rate=input_rate, file=file)
  File "mic_vad_streaming.py", line 56, in __init__
    self.stream = self.pa.open(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```
I'm aware that ec2 instance doesn't have microphone or speaker, but I need to test this model's real-time performance on a GPU machine. Is there any way I can use this code to test on ec2 instance.

**Comment by lissyx** [comment]
> I'm able to get text output on my local machine from `mic_vad_streaming.py` by providing `.wav` file in `--file` argument. But while running this code on AWS ec2 instance and also Colab Notebook I'm getting this following error:
> 
> ```
> Traceback (most recent call last):
>   File "mic_vad_streaming.py", line 237, in <module>
>     main(ARGS)
>   File "mic_vad_streaming.py", line 174, in main
>     file=ARGS.file)
>   File "mic_vad_streaming.py", line 107, in __init__
>     super().__init__(device=device, input_rate=input_rate, file=file)
>   File "mic_vad_streaming.py", line 56, in __init__
>     self.stream = self.pa.open(**kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/pyaudio.py", line 750, in open
>     stream = Stream(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/pyaudio.py", line 441, in __init__
>     self._stream = pa.open(**arguments)
> OSError: [Errno -9996] Invalid input device (no default output device)
> ```
> 
> I'm aware that ec2 instance doesn't have microphone or speaker, but I need to test this model's real-time performance on a GPU machine. Is there any way I can use this code to test on ec2 instance.

Don't use this example and use other deepspeech tools ? This specific example requires a microphone.

**Comment by swapnil3597** [comment]
I was going through other examples, `vad_transcriber/` would work for me as it is using generator for to generate segment with VAD. 
Thanks :)
