### ISSUE TITLE
.Net example not works with custom LM

### ISSUE THREAD

**Issue by inomax5** [mozilla/DeepSpeech-examples#28]
Hello.

I'm trying to use custom [this](https://github.com/GeorgeFedoseev/DeepSpeech/releases/tag/1.0) language model in .Net example WFP project. 
This model has graph file, futhermore i had made bpmm graph file.
But when i use them i get error:

> Error failed to create session.

Stack trace:

  > at DeepSpeechClient.DeepSpeech.EvaluateResultCode(ErrorCodes resultCode)
>    at DeepSpeechWPF.App.OnStartup(StartupEventArgs e) in D:\Temp\DeepSpeech-examples-r0.6\net_framework\DeepSpeechWPF\App.xaml.cs:line 25

Could somebody be kind to check the model and explain what's wrong with this model above?

PS. During using of pre-trained English mozilla's model from [here](https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/deepspeech-0.6.1-models.tar.gz) all goes Ok.

**Comment by lissyx** [comment]
> I'm trying to use custom [this](https://github.com/GeorgeFedoseev/DeepSpeech/releases/tag/1.0) language model

This does not mention any deepspeech version, but given it was produced on june 2018 it's very likely not to be compatible with 0.6 version used here.
