### ISSUE TITLE
Description of .net DeepSpeechClient.CreateModel previous version

### ISSUE THREAD

**Issue by inomax5** [mozilla/DeepSpeech-examples#29]
I need to downgrade version of deepspeech in WPF example. But i can't to find repo with description of required params of DeepSpeechClient.CreateModel(string aModelPath, uint aNCep, uint aNContext, string aAlphabetConfigPath, uint aBeamWidth) regards 0.5.1 and below.

What exactly these params -  uint aNCep, uint aNContext about and where i can find them if i use third-party LM?

**Comment by lissyx** [comment]
> I need to downgrade version of deepspeech in WPF example. But i can't to find repo with description of required params of DeepSpeechClient.CreateModel(string aModelPath, uint aNCep, uint aNContext, string aAlphabetConfigPath, uint aBeamWidth) regards 0.5.1 and below.
> 
> What exactly these params - uint aNCep, uint aNContext about and where i can find them if i use third-party LM?

Please have a look at the DeepSpeech codebase for that release: https://github.com/mozilla/DeepSpeech/tree/v0.5.1/native_client/dotnet

**Comment by inomax5** [comment]
@lissyx Thanks. I've forked repo. And see 👍 
        /// <param name="aNCep">The number of cepstrum the model was trained with.</param>
        /// <param name="aNContext">The context window the model was trained with.</param>

How can i get these values? In what command these params sets when model is training (because i should ask model creator about that)? 
Am i right, that i can't use the model if i'll not find what values were in these params?

**Comment by lissyx** [comment]
> @lissyx Thanks. I've forked repo. And see +1
> /// The number of cepstrum the model was trained with.
> /// The context window the model was trained with.
> 
> How can i get these values? In what command these params sets when model is training (because i should ask model creator about that)?
> Am i right, that i can't use the model if i'll not find what values were in these params?

Just look at the values from DeepSpeech default value. If it still does not work, then you need to reach to the people sharing the model...

**Comment by inomax5** [comment]
Yep, i.ve got these values:
25 for cepstrum 
9 for context

I've tried on all versions of deepspeech that exists in nuget.
For lower versions i got error:

> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Stacktrace:

   

> at DeepSpeechClient.NativeImp.DS_CreateModel(String aModelPath, UInt32 aNCep, UInt32 aNContext, String aAlphabetConfigPath, UInt32 aBeamWidth, ModelState**& pint)
>    at DeepSpeechClient.DeepSpeech.CreateModel(String aModelPath, UInt32 aNCep, UInt32 aNContext, String aAlphabetConfigPath, UInt32 aBeamWidth)
>    at DeepSpeechWPF.App.OnStartup(StartupEventArgs e) in D:\Temp\DeepSpeech-examples-r0.6\net_framework\DeepSpeechWPF\App.xaml.cs:line 25
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at DeepSpeechWPF.App.Main()

**Comment by reuben** [comment]
Not a bug, please ask whoever gave you this model what the hyperparameters are. Newer versions of DeepSpeech embed these values directly in the model so that you don't need to specify them, but for v0.5.1 there's no way around knowing them.

**Comment by carlfm01** [comment]
Hello @inomax5, as tip, please make sure that your setup is working with a recent and official model.

**Comment by inomax5** [comment]
So, i asked model creator about these  params. I gave you them. I've tried your app with all versions of deepspeech from nuget. And no one works1! Model link is [here](https://github.com/GeorgeFedoseev/DeepSpeech/releases/tag/1.0). If it is not a bug, so what is really it? You check it yourself. 
But tell me that System.AccessViolationException occurs exactly regards to params
/// The number of cepstrum the model was trained with.
/// The context window the model was trained with.

And tell me after check that is NOT A BUG!

**Comment by inomax5** [comment]
@carlfm01 I described it in [issue](https://github.com/mozilla/DeepSpeech-examples/issues/28) but its seems normally just closed issues.

**Comment by carlfm01** [comment]
Didn't see the other issue, @inomax5 it is working with other clients?

**Comment by lissyx** [comment]
> So, i asked model creator about these params. I gave you them. I've tried your app with all versions of deepspeech from nuget. And no one works1! Model link is [here](https://github.com/GeorgeFedoseev/DeepSpeech/releases/tag/1.0). If it is not a bug, so what is really it? You check it yourself.
> But tell me that System.AccessViolationException occurs exactly regards to params
> /// The number of cepstrum the model was trained with.
> /// The context window the model was trained with.
> 
> And tell me after check that is NOT A BUG!

This app and bindings are for deepspeech version released after your model was produced, that's already a huge source of bugs that we can't fix anyway.

**Comment by inomax5** [comment]
@lissyx  Ok. Thanks a lot anyway.
I will try to use lower versions of bin deepspeech command for that model. If it will work, i'll make .net core service that will execute bash.

**Comment by inomax5** [comment]
> t
It works with official english model as well.

**Comment by lissyx** [comment]
Why not train on current version instead?

**Comment by inomax5** [comment]
https://github.com/GeorgeFedoseev/DeepSpeech
This model pre-trained on big voice data, much more primary data then even offcial Mozilla's dataset. It will take much time even to download and process data.

**Comment by lissyx** [comment]
> https://github.com/GeorgeFedoseev/DeepSpeech
> This model pre-trained on big voice data, much more primary data then even offcial Mozilla's dataset. It will take much time even to download and process data.

Yes, this person made several contribution to the official repo. That being said, even if it's a lot of data, this is the only sane and efficient way to tackle this problem: the .Net bindings were non-existing at the time of this model's release. You will just create some broken half-way non-future-proof working setup.

I don't know why this contributor is not active anymore, but trying to bend .Net's bindings to work like you are trying is just putting pressure on other contributor for something they mostly cannot help with.

Have you tried contacting George? Maybe he'd be interested in upgrading and releasing new versions of his model ? Maybe he knows of people doing it ? Maybe you could try and join forces with other people working on some russian model (there were several questions around that on Discourse, so I doubt you are alone).

**Comment by inomax5** [comment]
Yes, i saw that people tried to train their own models. What i've been trying to do on current version of deepSpech with official voice dataset. But i stuck on model training process. Command just ends process after begin, with no message or errrors. I think this is another problem wich should be  considered on Discourse.
