### ISSUE TITLE
Error when starting the app: TypeError [ERR_INVALID_ARG_TYPE]: The “path” argument must be of type string

### ISSUE THREAD

**Issue by JosipSylo** [mozilla/DeepSpeech-examples#32]
If anyone else bumps into it, here is a fix that worked for me:
https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re

It might be worth pushing that change to this repo as well.

**Comment by lissyx** [comment]
> If anyone else bumps into it, here is a fix that worked for me:
> https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re

This does not mention anything related to any DeepSpeech example, can you clarify proper STR ? Which of the example exposes that ? What did you do ?


> It might be worth pushing that change to this repo as well.

If you have the issue and the fix, why don't you push a PR ?

**Comment by reuben** [comment]
Will be fixed as part of https://github.com/mozilla/DeepSpeech/issues/2956

**Comment by reuben** [comment]
Oh, wait, no, that's in this repo.
