### ISSUE TITLE
"modelStream.feedAudioContent(data) is not a function" in web_microphone_websocket example

### ISSUE THREAD

**Issue by xfiderek** [mozilla/DeepSpeech-examples#33]
function Model.createStream() returns object with undefined functions, i.e. Stream.feedAudioContent and Stream.finishStream can not be called on the returned stream object.
If it would save any of your time - console.log(Model.createStream()) returns "SwigProxy {}"

**Comment by reuben** [comment]
Thanks for the report, this is a DeepSpeech bug so closing here and opening there.

**Comment by reuben** [comment]
@xfiderek I've landed a fix and made a new alpha. You should be able to install version 0.7.1-alpha.0 to verify. We'll do a 0.7.1 release some time next week.
