### ISSUE TITLE
Cannot yarn start for Deepspeech web-microphone-socket react example

### ISSUE THREAD

**Issue by asyrafzlkln96** [mozilla/DeepSpeech-examples#38]
Hi, I'm having an error when trying to run yarn start.
The server works well and running when I run node server.js.

This is the log for yarn start :
yarn run v1.22.4
error An unexpected error occurred: "/home/asyraf/Desktop/jstutorial/package.json: Unexpected token < in JSON at position 0".
info If you think this is a bug, please open a bug report with the information provided in "/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Why do you think this happened? I tried uninstall and reinstalling yarn and didn't work.

Thanks,
Asyraf.

**Comment by asyrafzlkln96** [comment]
Okay it seems that the error have been solved. I used npm start instead of yarn start.

Now I got a new error for the React client, when I start recording. This is my log:

node server.js 
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-0-g3fbbca2
2020-05-03 11:26:14.663694: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Socket server listening on: 4000
client connected
client connected
.
[start](node:25582) UnhandledPromiseRejectionWarning: TypeError: modelStream.feedAudioContent is not a function
    at feedAudioContent (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:183:14)
    at processVoice (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:147:2)
    at /home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:48:5
(node:25582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
=(node:25582) UnhandledPromiseRejectionWarning: TypeError: modelStream.feedAudioContent is not a function
    at feedAudioContent (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:183:14)
    at processVoice (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:147:2)
    at /home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:48:5
(node:25582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
-(node:25582) UnhandledPromiseRejectionWarning: TypeError: modelStream.feedAudioContent is not a function
    at feedAudioContent (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:183:14)
    at processSilence (/home/asyraf/Desktop/jstutorial/DeepspeechReactJS/server.js:86:3)

**Comment by siddiqaa** [comment]
I have the same issue. This could be related to work done for 0.7  - "Moved Stream-relative functions to be methods in the Stream object in Python and JavaScript bindings[27]." in[ pull request 2792](https://github.com/mozilla/DeepSpeech/pull/2792). Perhaps a missing change in the JavaScript bindings?

**Comment by reuben** [comment]
The `npm start` error is some weird `react-scripts` bug, reported in #32 and already fixed here in the examples repo. Update your checkout, do `npm install` again to update and `npm start` should work again. The `TypeError` is #33. It was fixed and released as an alpha version in `deepspeech==0.7.1-alpha.0`, and should go into a bugfix `0.7.1` release sometime soon (but you can already install the alpha to work around the problem).

**Comment by reuben** [comment]
Closing since this was covered by other issues.
