### ISSUE TITLE
This issue is showing for me. What should i do sir ?! 

### ISSUE THREAD

**Issue by MjSiva398** [mozilla/DeepSpeech-examples#4]
usage: example_DS.py [-h] [-v VAD_AGGRESSIVENESS] [--nospinner] [-w SAVEWAV]
                     [-f FILE] -m MODEL [-l LM] [-t TRIE] [-d DEVICE]
                     [-r RATE] [-la LM_ALPHA] [-lb LM_BETA] [-bw BEAM_WIDTH]
example_DS.py: error: the following arguments are required: -m/--model

Process finished with exit code 2

**Comment by lissyx** [comment]
>  example_DS.py: error: the following arguments are required: -m/--model

What is unclear in this error ? Are you passing `-m` parameter ?

**Comment by MjSiva398** [comment]
Yes now am getting clear,
Thanks,.
