### ISSUE TITLE
modelStream.finishStream is not a function

### ISSUE THREAD

**Issue by Deryuu** [mozilla/DeepSpeech-examples#46]
In example "web_microphone_websocket" when i hit stop recording it gives me following error

"modelStream.finishStream is not a function"

I guess it's also a DeepSpeech related bug like in #33. Could it be?

**Comment by FabriceEll** [comment]
Like in #33  the problem is fixed in Version 0.7.1 of DeepSpeech, if you want to fix it before they release the final v0.7.1 you can change the package.json to "deepspeech": "^0.7.1-alpha.2" and for me it worked

**Comment by Deryuu** [comment]
thanks a lot, worked  <3
