### ISSUE TITLE
Cannot find module '/var/www/deepspeech/DeepSpeech-examples/nodejs_wav/node_modules/deepspeech/lib/binding/v0.7.0/linux-x64/node-v57/deepspeech.node'

### ISSUE THREAD

**Issue by praine** [mozilla/DeepSpeech-examples#48]
Hi There,

I get this error message when trying to use the nodejs_wav.
I have checked the contents of this folder and I can see:

- node-v64
- node-v67
- node-v72
- node-v79

But there is no "node-v57" as mentioned in this error message.
The node version I am running on my linux machine is v8.10.0

What should I do to resolve this issue? Downgrade my node version to v79? or v57?

Cheers

Paul

**Comment by reuben** [comment]
NodeJS 8 is no longer maintained, and thus we no longer support it. You should upgrade to a supported release: https://nodejs.org/en/about/releases/

**Comment by SuvigyaJain1** [comment]
I am on node v16.0.0 and am getting the exact same error.
I did nothing but clone this repo. cd to node_wav and run node index.js
I do have the latest model and scorer installed in /models folder

**Comment by lissyx** [comment]
> I am on node v16.0.0 and am getting the exact same error.
> I did nothing but clone this repo. cd to node_wav and run node index.js
> I do have the latest model and scorer installed in /models folder

There is no support for NodeJS v16.0 with versions r0.9. Please contribute: https://github.com/mozilla/DeepSpeech/issues/3606

**Comment by burgil** [comment]
How do I add support for node-v93? how do I build the file deepspeech.node?
https://github.com/mozilla/DeepSpeech-examples/issues/138

**Comment by neural-loop** [comment]
Also facing same issue: How do I add support for node-v93? how do I build the file deepspeech.node?

**Comment by reuben** [comment]
FYI: [Coqui STT](https://github.com/coqui-ai/STT) has support for NodeJS 12 to 17 and ElectronJS 12 to 15 (up to 16 on main branch, has to be released). Upgrading from DeepSpeech to Coqui STT should be very simple, just replace `import deepspeech` with `import stt`, if you were already using v0.9.3 of DeepSpeech, and make sure you're using TFLite models, not `.pb`. or `.pbmm`.

**Comment by neural-loop** [comment]
Thanks @reuben . I figured out that I had to change my node version to get it going. I'll try Coqui out too!

**Comment by pkirklewski** [comment]
node -v   v19.3.0
Error: The module '\\?\C:\Users\user\Desktop\JavaScript Projects\DeepSpeech\node_modules\deepspeech\lib\binding\v0.9.3\win32-x64\node-v111\deepspeech.node'

Is there no support for node 19.x ? 
How can I recover from this?

**Comment by pkirklewski** [comment]
For those who are still struggling in 2023: 

1. Install nvm https://github.com/coreybutler/nvm-windows/releases/download/1.1.10/nvm-setup.exe
2. nvm install 10
3. nvm use 10.23.1 

After switching to node 10.23.1 my script stops complaining about the missing module. It now says: 

node .\index.js
TensorFlow: v2.3.0-6-g23ad988fcd
DeepSpeech: v0.9.3-0-gf2e9c858
Not found: NewReadOnlyMemoryRegionFromFile failed to Create/Open: ./deepspeech-0.9.3-models.pbmm : The system cannot find the file specified.
; No such file or directory

C:\Users\user\Desktop\JavaScript Projects\DeepSpeech\node_modules\deepspeech\index.js:106
            throw `CreateModel failed: ${binding.ErrorCodeToErrorMessage(status)} (0x${status.toString(16)})`;
            ^
CreateModel failed: Failed to initialize memory mapped model. (0x3000)

**Comment by pkirklewski** [comment]
Downloaded 
deepspeech-0.9.3-models.pbmm  deepspeech-0.9.3-models.tflite 
from https://github.com/mozilla/DeepSpeech/releases and placed them in the same folder where my index.js is sitting. 
Now I get a new issue: 

...node_modules\deepspeech\index.js:188
            throw `EnableExternalScorer failed: ${binding.ErrorCodeToErrorMessage(status)} (0x${status.toString(16)})`;
            ^
EnableExternalScorer failed: Invalid scorer file. (0x2002)

**Comment by pkirklewski** [comment]
For those who are still struggling in 2023:

npm install deepspeech 
npm install fluent-ffmpeg
wget https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.pbmm
wget https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.tflite
wget https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.scorer
Install nvm https://github.com/coreybutler/nvm-windows/releases/download/1.1.10/nvm-setup.exe
nvm install 10
nvm use 10.23.1

node index.js 

It works for me on WIndows 11.
