### ISSUE TITLE
AttributeError: module 'deepspeech' has no attribute 'Model'

### ISSUE THREAD

**Issue by Mchar7** [mozilla/DeepSpeech-examples#5]
I'm fairly new to Python and I'm assuming it's an easy fix, but I'm getting the following error on the "Microphone VAD streaming" example:

`Initializing model...
INFO:root:ARGS.model: deepspeech-0.6.0-models/output_graph.pb
Traceback (most recent call last):
  File "deepspeech.py", line 237, in <module>
    main(ARGS)
  File "deepspeech.py", line 164, in main
    model = deepspeech.Model(ARGS.model, ARGS.beam_width)
AttributeError: module 'deepspeech' has no attribute 'Model'
`

I'm running the command "python3 deepspeech.py -m deepspeech-0.6.0-models/". The models are in the directory that I passed and I haven't changed the code from the example given.
I'd appreciate some help if someone could ;)

**Comment by reuben** [comment]
This looks like a problem with the installation of the deepspeech package. Could you try reinstalling things on a fresh virtual environment? If it still happens, could you post the full output?

**Comment by Mchar7** [comment]
Thanks for the help. I hope this isn't too verbose, but here is the steps I took:

`[MYUSERNAME@MYPC MYPROJECTFOLDER]$ virtualenv -p python3 $HOME/tmp/deepspeech-venv/
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/MYUSERNAME/tmp/deepspeech-venv/bin/python3
Not overwriting existing python script /home/MYUSERNAME/tmp/deepspeech-venv/bin/python (you must use /home/MYUSERNAME/tmp/deepspeech-venv/bin/python3)
Installing setuptools, pip, wheel...
done.`

`[MYUSERNAME@MYPC MYPROJECTFOLDER]$ source $HOME/tmp/deepspeech-venv/bin/activate`

`(deepspeech-venv) [MYUSERNAME@MYPC MYPROJECTFOLDER]$ sudo pip3 install --force deepspeech
Collecting deepspeech
  Using cached https://files.pythonhosted.org/packages/f7/ad/cde815d6b3745f506184c095a8021ebefddc04981d61c780d04ef1224024/deepspeech-0.6.0-cp38-cp38-manylinux1_x86_64.whl
Collecting numpy>=1.17.3
  Using cached https://files.pythonhosted.org/packages/d7/6a/3fed132c846d1e47963f30376cc041e9dd586d286d931055ad06ff65c6c7/numpy-1.17.4-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: numpy, deepspeech
  Found existing installation: numpy 1.17.4
    Uninstalling numpy-1.17.4:
      Successfully uninstalled numpy-1.17.4
  Found existing installation: deepspeech 0.6.0
    Uninstalling deepspeech-0.6.0:
      Successfully uninstalled deepspeech-0.6.0
Successfully installed deepspeech-0.6.0 numpy-1.17.4`

`(deepspeech-venv) [MYUSERNAME@MYPC MYPROJECTFOLDER]$ deepspeech --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie --audio audio/2830-3980-0043.wav
Loading model from file deepspeech-0.6.0-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.0-0-g6d43e21
Loaded model in 0.0658s.
Loading language model from files deepspeech-0.6.0-models/lm.binary deepspeech-0.6.0-models/trie
Loaded language model in 0.000287s.
Running inference.
experience proof less
Inference took 2.650s for 1.975s audio file.`

`(deepspeech-venv) [MYUSERNAME@MYPC MYPROJECTFOLDER]$ python3 deepspeech.py --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie
Initializing model...
INFO:root:ARGS.model: deepspeech-0.6.0-models/output_graph.pbmm
**Traceback (most recent call last):
  File "deepspeech.py", line 237, in <module>
    main(ARGS)
  File "deepspeech.py", line 164, in main
    model = deepspeech.Model(ARGS.model, ARGS.beam_width)
AttributeError: module 'deepspeech' has no attribute 'Model'**`

As you can see, it worked fine when using the DeepSpeech example from the main repo's README, but when I executed transcribe.py (which is an exact copy of mic_vad_streaming.py) it gave the same error as before.

P.S.: I might be AFK for a little bit before I get to work on it again.

**Comment by lissyx** [comment]
You are setting up a virtual env and still use `sudo` to run pip. This can only lead to mess and inconsistent setup

**Comment by Mchar7** [comment]
> You are setting up a virtual env and still use `sudo` to run pip. This can only lead to mess and inconsistent setup

Good point, I didn't even consider that.
I created a different venv, installed all the needed libraries using `pip` without `sudo` and ran it again but I keep getting the same error.

**Comment by lissyx** [comment]
> > You are setting up a virtual env and still use `sudo` to run pip. This can only lead to mess and inconsistent setup
> 
> Good point, I didn't even consider that.
> I created a different venv, installed all the needed libraries using `pip` without `sudo` and ran it again but I keep getting the same error.

Can you also ensure the `python3` command you issue does properly load the expected python from virtualenv ? Can you verify `pip list` as well ?

That's really really weird ...

**Comment by lissyx** [comment]
> (deepspeech-venv) [MYUSERNAME@MYPC MYPROJECTFOLDER]$ python3 deepspeech.py --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie Initializing model... INFO:root:ARGS.model: deepspeech-0.6.0-models/output_graph.pbmm **Traceback (most recent call last): File "deepspeech.py", line 237, in <module> main(ARGS) File "deepspeech.py", line 164, in main model = deepspeech.Model(ARGS.model, ARGS.beam_width) AttributeError: module 'deepspeech' has no attribute 'Model'**

WAIT WAIT WAIT

What is this `deepspeech.py` ? Where does it comes from ? That's not in any of the examples as much as I can see.

**Comment by Mchar7** [comment]
> > (deepspeech-venv) [MYUSERNAME@MYPC MYPROJECTFOLDER]$ python3 deepspeech.py --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie Initializing model... INFO:root:ARGS.model: deepspeech-0.6.0-models/output_graph.pbmm **Traceback (most recent call last): File "deepspeech.py", line 237, in  main(ARGS) File "deepspeech.py", line 164, in main model = deepspeech.Model(ARGS.model, ARGS.beam_width) AttributeError: module 'deepspeech' has no attribute 'Model'**
> 
> WAIT WAIT WAIT
> 
> What is this `deepspeech.py` ? Where does it comes from ? That's not in any of the examples as much as I can see.

It's working now. I named my testing file `deepspeech.py` just to test it. I didn't know that you couldn't name a python file the same as a library being used in it. If I name it to anything else, it works.

Just curious, why is it that the filename would affect whether or not the program works?

**Comment by lissyx** [comment]
> Just curious, why is it that the filename would affect whether or not the program works?

It makes sense, the `from deepspeech import Model` would consider `deepspeech` module to be your `deepspeech.py` :-)
