### ISSUE TITLE
How to run android mic streaming without LM and true

### ISSUE THREAD

**Issue by omerarshad** [mozilla/DeepSpeech-examples#50]
How to run Speech to text in android without using LM and trie file?

**Comment by reuben** [comment]
Change the code to not load the scorer.

**Comment by omerarshad** [comment]
I am using deepspeech 0.6.1, and if you don't input LM and Trie file, it gives error.

**Comment by omerarshad** [comment]
Have you tried or just giving suggestions?

**Comment by reuben** [comment]
It does work, the LM has always been optional.

**Comment by omerarshad** [comment]
model?.enableDecoderWihLM(languageModelPath, triePath, LM_ALPHA, LM_BETA)
if you dont pass Languagemodelparh and trie path, it gives error

**Comment by reuben** [comment]
The decoder with LM is disabled by default. Just don't call that at all...
