### ISSUE TITLE
taskcluster has moved in original DeepSpeech repo

### ISSUE THREAD

**Issue by GaurangTandon** [mozilla/DeepSpeech-examples#55]
The taskcluster directory is now at `DeepSpeech` and not `DeepSpeech/ds` as is currently mentioned in the `tests.sh` file (r0.7 branch, line 7)

**Comment by lissyx** [comment]
And? It's for CI, you don't need to care about that...

**Comment by GaurangTandon** [comment]
I thought I can run test.sh in order to do a sample run of the mic example. Apologies for the confusion! (This is why I was running `test.sh` so far, which called `tests.sh`)
