### ISSUE TITLE
Value of TASK_ID, DS_VERSION in tests.sh

### ISSUE THREAD

**Issue by GaurangTandon** [mozilla/DeepSpeech-examples#56]
The `TASK_ID`, `DS_VERSION`, etc. environment variables are not mentioned anywhere in the repo but are being used in the `tests.sh` file. Could you please elaborate on what values to input for them?

**Comment by reuben** [comment]
The `tests.sh` and `test.sh` files are supposed to be run by the CI automation on the DeepSpeech repo, not directly by users. Just follow the respective READMEs.

**Comment by GaurangTandon** [comment]
I thought I can run test.sh in order to do a sample run of the mic example. Apologies for the confusion!
