### ISSUE TITLE
Mic vad streaming Python file does not work with wav file input

### ISSUE THREAD

**Issue by GaurangTandon** [mozilla/DeepSpeech-examples#57]
As far as I have understood, file input is supposed to be a pre-recorded wav file, for example, the ones given in audio-0.7.1.tar.gz [here](https://github.com/mozilla/deepspeech/releases). The `mic_vad_streaming.py` will take that wav file, and the model and scorer, and output transcription for that audio. However, in my case, no transcription happens and the script exits with zero exit code!

```
$ python mic_vad_streaming.py -v 2 -m ~/DeepSpeech/models/models.pbmm -s ~/DeepSpeech/models/models.scorer -f ~/DeepSpeech/audio/2830-3980-0043.wav 

Initializing model...
INFO:root:ARGS.model: /home/gt/otherrepos/DeepSpeech/models/models.pbmm
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.1-0-g2e9c281
2020-05-27 16:53:44.182279: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:root:ARGS.scorer: /home/gt/otherrepos/DeepSpeech/models/models.scorer
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Listening (ctrl-C to exit)...
```

This is the complete log. The models are latest v0.7.0 files, and audio file is  one of the samples from the [release page](https://github.com/mozilla/deepspeech/releases). What might be going wrong?

-----

PS: I am able to get transcription from my microphone when running without the `-f` argument.

**Comment by GaurangTandon** [comment]
I am not sure whether to close this issue or reopen. I actually got my stuff to work using the `vad_transcriber` example, however, I believe the issue still exists because `mic_vad_transcriber` takes a file argument and does not behave as expected. I will leave upto the maintainers to decide what to do.

**Comment by reuben** [comment]
This example is focused on the microphone, as the name implies. The loading from file mode was added so that the code can be exercised in CI. I'm not sure what this is supposed to be doing, @lissyx might know more since he added this code. But if this is working as intended with the microphone then I'd say there's no issue.
