### ISSUE TITLE
donet example not working unable to load DLL 'libdeepspeech.so'

### ISSUE THREAD

**Issue by honeybadger66** [mozilla/DeepSpeech-examples#63]
Hi;
I downloaded the examples to try, remove the ClientDeepSpeech project and installed the NuGet.  Also, downloaded the .pbmm file.  When I try to run,  I get unable to load DLL 'libdeepspeech.so', the specified module could not be found(exception from HRESULT: 0x8007007E).
It seems I'm missing something.
Thank you,
Hanna

**Comment by honeybadger66** [comment]
Hi;
Never mind I figure it out.  I copied the libdeepspeech.so from the packages/DeepSpeech/build to the bin/Debug folder.
Thank you.
Hanna

**Comment by carlfm01** [comment]
Please share more information, like Windows version, Visual Studio version, NuGet version, DS version, how you installed DS via nuge console or vs?

**Comment by honeybadger66** [comment]
Sorry, Windows 10, Visual Studio 2109, DS version 0.7.  Installed DS by downloading it from GitHub https://github.com/mozilla/DeepSpeech-examples.
Thank you.
