### ISSUE TITLE
getting very bad transcript while live streaming on r0.6 version node js socket api

### ISSUE THREAD

**Issue by alamnasim** [mozilla/DeepSpeech-examples#66]
Hi,
I have trained my custom model DeepSpeech 0.6.1 on my own data from scratch.

I have getting good accuracy while inference using deepspeech binary (testing wer: 0.18).

When i try r0.6 node js socket api and also mic vad streaming using my own data and lm, I am getting very bad transcript.

It does not capture any word, it just give me an output of same garbage word for each and every spoken word.

My predicted transcripts:

haan
haan haan
haan haan haan ...

I saved recorded audio and listen it was of very good quality and when i infer trans from deepspeech binary using the command:
deepspeech --model model_path --lm lm_path --trie trie_path --audio audio_path

It gives me very good transcripts.

So I am not able to understand why this happens with r0.6.
when I test with 0.5.1 model example of mic vad streaming, then I am getting good accuracy.

Can anyone help me to resolve this.
Why I am getting bad transcript on r0.6 node js socket api as well as mic vad streaming.

Thanks

**Comment by lissyx** [comment]
>  Why I am getting bad transcript on r0.6 node js socket api as well as mic vad streaming.

no idea, have you checked the parameters like lm etc?

**Comment by alectrocute** [comment]
You’re probably referencing the wrong model in the example projects.

**Comment by alamnasim** [comment]
This problem was resolved by checking the model and recorded audio sampling rate.
Thanks.
