### ISSUE TITLE
mic_vad_streaming - not picking up any audio from the microphone

### ISSUE THREAD

**Issue by vgoklani** [mozilla/DeepSpeech-examples#7]
Ran this on my macbook pro, and it wasn't picking up any audio from the built-in microphone. I used device = None, then tried device = 0,

I ran this: https://gist.github.com/mabdrabo/8678538

to confirm that pyaudio works and was installed correctly. It's able to pickup audio from the microphone. 

Any ideas?

**Comment by lissyx** [comment]
> Ran this on my macbook pro, and it wasn't picking up any audio from the built-in microphone. I used device = None, then tried device = 0,
> 
> I ran this: https://gist.github.com/mabdrabo/8678538
> 
> to confirm that pyaudio works and was installed correctly. It's able to pickup audio from the microphone.
> 
> Any ideas?

What's giving `pyaudio.PyAudio.get_device_info_by_index()` ?

Are https://github.com/mozilla/DeepSpeech-examples/blob/r0.6/mic_vad_streaming/mic_vad_streaming.py#L56-L57 reached and working ?

What makes you think `it wasn't picking up any audio from the built-in microphone` ?

**Comment by vgoklani** [comment]
I take it back, it's picking up audio (i checked the frames directly) but not outputting anything. 

It just says Listening.
