### ISSUE TITLE
Improve speech to text deep speech 

### ISSUE THREAD

**Issue by doctorwho-123** [mozilla/DeepSpeech-examples#96]
Hello . When I downloaded deepspeech and run it on Windows, it unfortunately turned bad speech into text.

For example, when I say: 
HI ----> i
you are ->you are 

hello -> halow 

How can I increase the accuracy or efficiency of speech to text conversion?

I just want to use only the Deep Speech model and I do not want to teach on any datasets? Is there a way or not?

When I say a word through a microphone, do I already have to make certain settings in the Windows environment?...

**Comment by reuben** [comment]
Use Discourse for support requests.
