### ISSUE TITLE
ERROR: Model provided has model identifier

### ISSUE THREAD

**Issue by xMpOnEx** [mozilla/DeepSpeech-examples#99]
I've downloaded deepspeech-0.9.2-models.pbmm and deepspeech-0.9.2-models.scorer

IF I call deepspeech.model(deepspeech-0.9.2-models.pbmm) i got error:

ERROR: Model provided has model identifier 'u/3▒', should be 'TFL3'

How I've to use it right the deepspeech-0.9.2-models.pbmm and deepspeech-0.9.2-models.scorer?

**Comment by reuben** [comment]
https://deepspeech.readthedocs.io/en/v0.9.2/USING.html
